export const FACEBOOK_APP_ID = process.env.NEXT_PUBLIC_FACEBOOK_APP_ID
export const FACEBOOK_APP_SECRET = process.env.NEXT_PUBLIC_FACEBOOK_APP_SECRET
export const FACEBOOK_CALLBACK_URL = process.env.NEXT_PUBLIC_FACEBOOK_CALLBACK_URL
export const FACEBOOK_API_VERSION = process.env.NEXT_PUBLIC_FACEBOOK_API_VERSION

